### ISSUE TITLE
idea: toggle between visible, invisible and hidden

### ISSUE THREAD

**Issue by johanneseckert** [preciousforever/sketch-layer-visibility#1]
I use bounding boxes to export buttons that need the same visual position and cannot be exported by just the artwork layers (e.g. a reload button doesn't sit centered in the bounding box because of its assymetric shape

What I use to enable layer exporting (no slices) is a non-visible bounding box (no fill etc) that will make sure the icon gets exported at 44×44pt.
This is also handy to space and position icons according to actual button positions.

Does that make sense?

**Comment by studiostoll** [comment]
But an "exportable" layer group ignores boundingBox layers, no matter if they are invisible, fill=hidden or fill.opacity=0, doesn't it? Or what's your trick? :)

We also did "boundingBox" layers with "fill = off", but since the style properties of a rectangle are "read-only" via Sketch API, we did it with the layer visibility for the plugin.

We do not often export assets via exportable layer groups though, so it wasn't a real issue yet.

**Comment by johanneseckert** [comment]
yeah, you're right. a fill-les boundingBox is great for positioning elements on the canvas, but the export is still the bare icon.
for that, we need to create a slice the size of the boundingBox, isn't it?

I am still wondering why this isn't a native feature in sketch. And why are the style properties read-only @bomberstudios?

**Comment by bomberstudios** [comment]
Style properties are not read-only (unless I'm reading this thread wrong).

If you want to change, say, the opacity of a fill, you can do:

`[[[[layer style] fill] color] setAlpha:0.2]`

Generally speaking, a property called `propertyName` has to be set using a method named `setPropertyName`. For fills, there's a property called `isEnabled`, so if you wanted to disable a fill, you should do:

`[[[layer style] fill] setIsEnabled:false]`

Hope it helps!

**Comment by studiostoll** [comment]
thanks a lot @bomberstudios! I think we've been misguided by the doc here:
http://bohemiancoding.com/sketch/support/developer/03-reference/MSLayer.html

@frischmilch I think the "boundingBox" thing doesn't have to be a native feature, it's a pretty simple script and you can assign any shortcut. However, it would be great if the bounds of a rectangle with its fill disabled would be regarded when exporting via "exportable layer groups". This would make the boundingBox approach much more valuable.

**Comment by johanneseckert** [comment]
you're script is fine! I was just thinking that as a tool used for UI design, Sketch could have some behaviors that do this »natively«, since it's something you would do in code when developing anways and my designs are much more accurate if I also respect the bounding box of the button. And the developers love it seeing spec'd out too :-)
