### ISSUE TITLE
crashes with too many involved layers

### ISSUE THREAD

**Issue by studiostoll** [preciousforever/sketch-layer-visibility#2]
Once there are too many layers (eg. "boundingBox") to toggle, the plugin crashes. we'll try to set a timeout every n layers.

workaround: spread work across several pages.

**Comment by studiostoll** [comment]
interesting: if the script is being executed from within the "custom script" console within Sketch, it doesn't crash.

here's the script code that let's you print the amount of triggered layers:

``` CocoaScript
var searchPattern = "boundingBox"; 
var allArtboards = [[doc currentPage] artboards]

for (var i=0; i < [allArtboards length]; i++){ 
var artboard = [allArtboards objectAtIndex:i] 
var children = [artboard children]
var n = 0;
for (var j=0; j < [children length]; j++){ 
var child = [children objectAtIndex:j]; 
var name = [child name]; 
if(name.indexOf(searchPattern) == 0) { 

//this line toggles the visibility of layer starting with searchPattern
[child setIsVisible:![child isVisible]]

n++;

//this line prints the amount of searchPattern
print(n)
} 
} 
}
```

**Comment by studiostoll** [comment]
Seems to be a general issue related to parsing of the layer tree:
https://github.com/tisho/sketch-plugins/issues/2

**Comment by bomberstudios** [comment]
Interesting... Can you please provide us with a sample .sketch file that crashes when the plugin is run from the menu but not when it's run from the Custom Script window? That looks worth investigating...

Thanks in advance!

**Comment by studiostoll** [comment]
Hey @bomberstudios! I cannot send you the original file unfortunately, but I think I know a way to rebuild/reproduce the behavior. Where should I send it to?

**Comment by bomberstudios** [comment]
ale@bohemiancoding.com : )

**Comment by studiostoll** [comment]
@rockitbaby a thought: maybe we shouldn't have one plugin that toggles visibility, but rather one for setting visible, one for setting invisible. I'm not sure if this solves the crashing bug (we should try), but it fixes another issue: if a symbol contains boundingBoxes, and instances of this symbols are on different pages, the visibility quickly gets out of sync with toggling …

**Comment by lukasondre** [comment]
@nitrada The problem is likely caused by too many objects. You can fully fix this by using a predicate to filter the array of children.

The function below makes it easy to get layers with a name in the root layer. In your case, search for "boundingBox" on each page.

```
//get layers with name
function getLayersWithName(name, rootLayer, fullMatch) {

  //prepare predicate format
  var format = {
    key : '(name != NULL) && ' + ((fullMatch) ? '(name == %@)' : '(name like %@)'), 
    match : (fullMatch) ? name : ('*' + name + '*')
  };

  //get and return matches
  return jsArray(predicate(format, [rootLayer children]));
}
```

```
//filter array using predicate
function predicate(format, array) {

  //make sure that format is speficied
  if(!format || !format.key  || !format.match) return;

  //create predicate
  var predicate = NSPredicate.predicateWithFormat(format.key, format.match);

  //perform query
  var queryResult = array.filteredArrayUsingPredicate(predicate);

  //return result
  return queryResult;
}
```

```
//convert array to js array
function jsArray(array) {
  var length = [array count];
  var jsArray = [];

  while(length--) {
    jsArray.push([array objectAtIndex: length]);
  }
  return jsArray;
}
```

**Comment by studiostoll** [comment]
Thanks @lukas77me, we'll give it a try!

**Comment by lukasondre** [comment]
Glad it helped.
