### ISSUE TITLE
Toggle layer visibility no longer working

### ISSUE THREAD

**Issue by lucielca** [preciousforever/sketch-layer-visibility#5]
Hi,
In the last few days, the plugin has stopped working. The shortcut to view or hide layers no longer works. I'm running Sketch Version 3.4.2 (15857). Any ideas what could be causing this ?

Thanks / Lucie

**Comment by studiostoll** [comment]
Hi @lucielca, which version of the plugin are you using? The latest?

Also, if you have several sketch documents opened while using the plugin: try closing all except one and try the plugin again (there's a known quite nasty issue where plugin commands fired in document A might take action in document B.)

**Comment by lucielca** [comment]
Hi Christophe,

Thanks for your quick reply. I’m not sure which version I’m using, but it was downloaded sometime in the last few months. I see you have a more recent version, I’ll try with that one. I’ll also try your tip about keeping only one sketch document open.

**Comment by lucielca** [comment]
It’s the jan 28 2015 version.

**Comment by lucielca** [comment]
Hi,

It’s now working again with the latest version. However, the shortcut to toggle the visibility isn’t Command + L anymore, but Ctrl + Shift + R.

**Comment by studiostoll** [comment]
@lucielca the plugin does not have a default shortcut assigned actually! But you can set up whatever you like…

**Comment by lucielca** [comment]
Ok thanks. Would it be possible for you to explain how to do that ?

**Comment by yosyp** [comment]
@lucielca sure! This is what I did,

In Sketch, navigate to:
1. Plugins --> Manage Plugins
2. Select Sketch Layer Visibility --> Show Plugin Folder (in the gear dropdown)
3. Open sketchlayervisibility.sketchplugin in an editor like [Sublime](http://www.sublimetext.com/) 
4. In Sublime, navigate to [manifest.json](https://github.com/preciousforever/sketch-layer-visibility/blob/master/Sketch%20Layer%20Visibility.sketchplugin/Contents/Sketch/manifest.json)
5. In the `"shortcut"` parameter of each action enter the combination that you would like for that shortcut, for example `"cmd shift x"` or `"ctrl shift 1"`, etc.

**Comment by lucielca** [comment]
Thank you very much for the excellent instructions ! I was able to create a new shortcut.

**Comment by studiostoll** [comment]
sorry @lucielca for not getting back and thanks @yosyp for jumping in! :)
