### ISSUE TITLE
Idea: Add multiple layer masks

### ISSUE THREAD

**Issue by samuraydesign** [preciousforever/sketch-layer-visibility#6]
Is it hard to add something like this in settings?
`bounds*,specs*`
two different layer name masks to toggle layer visibility.

**Comment by rockitbaby** [comment]
@samuraydesign let me know what you think:

https://github.com/preciousforever/sketch-layer-visibility/releases/tag/1.2.0

**Comment by samuraydesign** [comment]
## This is super awesome! Thank you.

minor bug: It's not working if ',' symbol is not added at the end
`(specs*)` - not working `(specs*,)` - working

**Comment by rockitbaby** [comment]
thanks for reporting, bug should be fixed here:
- https://github.com/preciousforever/sketch-layer-visibility/releases/tag/1.2.1
